---
- hosts: all
  become: true
  become_user: piku
  tasks:
    - name: Make sure the bin directory exists
      file: path=~/bin state=directory
    
    - name: Install lein
      get_url: url=https://raw.githubusercontent.com/technomancy/leiningen/stable/bin/lein dest=~/bin/lein
    
    - name: Set lein Executable permissions
      file: path=~/bin/lein mode=0755

