name: Piku deployment testing
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    
    services:
      target:
        image: ubuntu:latest
        ports:
          - 22
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up SSH in target container
      run: |
        docker exec ${{ job.services.target.id }} apt-get update
        docker exec ${{ job.services.target.id }} apt-get install -y openssh-server
        docker exec ${{ job.services.target.id }} service ssh start
        docker exec ${{ job.services.target.id }} useradd -m testuser
        docker exec ${{ job.services.target.id }} bash -c 'echo "testuser:password" | chpasswd'
        docker exec ${{ job.services.target.id }} sed -i 's/PermitRootLogin prohibit-password/PermitRootLogin yes/' /etc/ssh/sshd_config
        docker exec ${{ job.services.target.id }} service ssh restart
    
    - name: Install SSH client
      run: sudo apt-get install -y openssh-client
    
    - name: Get target container IP
      run: echo "TARGET_IP=$(docker inspect -f '{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' ${{ job.services.target.id }})" >> $GITHUB_ENV
    
    - name: SSH into target and run command
      run: |
        sshpass -p 'password' ssh -o StrictHostKeyChecking=no testuser@$TARGET_IP "echo hello"
